# Generated by Django 4.2.6 on 2023-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
